name: CI-Develop

on:
  push:
    branches: [ develop ]

jobs:
  build_frontend:
    defaults:
      run:
        working-directory: './app'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install Packages
      run:  npm ci
    - name: Run Unit Tests
      run:  npm run test:unit
    - name: Build Frontend
      run:  npm run build
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: frontend-dist
        path: app/dist


  build_backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    env:
      PORT: 8080

    steps:
    - uses: actions/checkout@v2
    - name: Build using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  init_db:
    runs-on: ubuntu-latest
    env:
      MONGO_URL: ${{ secrets.MONGO_URL_STAGING }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install Packages
      run:  npm ci
    - name: Run Mongo-Init Script
      run:  npm run clearDB
      

  deploy_app:
    runs-on: ubuntu-latest
    needs: ['build_frontend', 'build_backend', 'init_db']

    steps:
    - uses: actions/checkout@v2
    - name: Download Frontend Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: frontend-dist
        path: app/dist
    - name: Tell Server to restart after Deployment
      run: mkdir tmp && touch tmp/restart.txt
    - name: 🚀 Deploy!
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.nailuj.net
        username: git
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./staging/
        exclude: .git* 
          - .git*/**
          - node_modules/**
          - node_modules/**/*
